### ISSUE TITLE
Choose a default build target

### ISSUE THREAD

**Issue by borishere** [idleberg/atom-build-sass#2]
Hi,
How to make `SCSS` a default build target? As for now it is `Sass`.

**Comment by idleberg** [comment]
Generally speaking, this is a feature request for the [build](https://github.com/noseglid/atom-build) package. The simplest workaround is to map a custom keybinding on your preferred build command.

In this particular case, one might argue that SCSS has been the Sass project's first class citizen for seven years, so reordering the build targets is reasonable.

**Comment by idleberg** [comment]
Closed in v0.11.0

**Comment by borishere** [comment]
Thanks for reordering:)
